language: R
cache: packages

warnings_are_errors: true

r_packages:
  - covr
  - lintr

before_script:
  - chmod +x ./deploy.sh

after_success:
  - ./deploy.sh
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'

after_failure:
- find *Rcheck -name '*fail' -print -exec cat '{}' \;
